# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  game_config = debug
endif
ifeq ($(config),release)
  game_config = release
endif

PROJECTS := game

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

game:
ifneq (,$(game_config))
	@echo "==== Building game ($(game_config)) ===="
	@${MAKE} --no-print-directory -C . -f game.make config=$(game_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f game.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   game"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"