(def window-width 400)
(def window-height 650)
(def window-title "super janet typist")
(def frames-per-second 60)
(def repository "assets/repository")
(def default-font "assets/font.ttf")
(def background-image "assets/background.png")
(def hud-image "assets/hud.png")
(def janet-image "assets/janet.png")
(def bullet-image "assets/bullet.png")
(def default-font-size 20)
(def default-font-spacing 1)